<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

print rex_warning('Achtung: Inkompatible Benutzerdaten!');

?>

<p>Die gewünschten Änderungen an dem Attribut führen dazu, dass einige Benutzerdaten
nicht mehr aktuell sind und <?

// Problembeschreibung

if ($datatypeChanged) {
	print 'die betreffenden Daten <strong>'.($convertible ? 'konvertiert' : 'gelöscht');
	print '</strong> werden müssen.';

	if (!$convertible) {
		print '<br />&nbsp;</p>';
		print rex_warning(implode("<br>\n", $messages));
	}
	else {
		print ' Diese Konvertierung ist automatisch möglich und wird vom System vorgenommen.';
		print '<br />&nbsp;</p>';
	}
}
else {
	print 'von den betreffenden Benutzern <strong>gelöscht</strong> werden müssen.';
	print ' Der verwendete Datentyp <strong>'.rex_translate(WV_Datatype::getTitle($newDatatype));
	print '</strong> hat folgendes Problem gemeldet, das er nicht ohne Ihre ';
	print 'Bestätigung korrigieren kann:<br />&nbsp;</p>';

	print rex_warning(implode("<br>\n", $messages));
}

// Betroffene Objekte auflisten

print '<p>Von dieser Änderung sind die folgenden Benutzer betroffen:</p>';
print '<ul style="margin:10px 0 10px 10px">';

if (empty($affected)) {
	print '<li style="list-style-type:disc;margin-left:10px;color:green">(keine)</li>';
}
else {
	foreach ($affected as $u) {
		print '<li style="list-style-type:disc;margin-left:10px">'.sly_html($u->getLogin()).'</li>';
	}
}

print '</ul>';

// Möglichkeiten zu reagieren anbieten

print '<p>Wenn Sie sicher sind, dass die betreffenden Daten ';

if ($convertible) {
	print 'konvertiert';
}
else {
	print 'von den zugewiesenen Benutzern gelöscht';
}

print ' werden sollen, klicken Sie bitte auf &quot;Ja&quot;.';

if (!$datatypeChanged) {
	print 'Der verwendete Datentyp wird versuchen, die Daten bestmöglich ';
	print 'zu konvertieren und nur die nötigsten Änderungen vorzunehmen.';
}

?>

Andernfalls gehen Sie bitte zurück und korrigieren Ihre Eingaben.<br />&nbsp;&nbsp;</p>

<form method="post" action="index.php">
	<p style="text-align: center;margin-bottom:10px;margin-top:1em">
		<input type="submit" value="Ja, betreffende Daten <?= $convertible ? 'konvertieren' : 'löschen' ?>" style="color:red;background:white;border:2px outset #F99;padding:3px" />
		oder
		<input type="button" style="color:green;background:white;border:2px outset #9F9;padding:3px" value="zurückgehen und korrigieren" onclick="javascript:history.go(-1)" />
	</p>

	<div>
		<input type="hidden" name="confirmed" value="1" />
		<? _WV16_FrontendUser::printPOSTData(); ?>
	</div>
</form>
