<?

WV_Redaxo::p(
	'Attribute sind die Eigenschaften, die Sie Ihren Benutzern zuweisen können. Hier '.
	'legen Sie fest, welche Attribute es gibt und wie diese gestaltet werden sollen. '.
	'Bitte beachten Sie, dass die Felder &quot;Login&quot; und &quot;Passwort&quot; '.
	'fest im System integriert sind und daher nicht geändert werden können.'
);

$base  = 'index.php?page=frontenduser&amp;subpage=attributes&amp;func=';
$id    = '<a href="'.$base.'add"><img src="media/metainfo_plus.gif" alt="" title="Hinzufügen" /></a>';
$table = new WV_Table('attrtable');
$table->addColumn(new WV_Table_Column($id, '', 'id', array('class' => 'rex-icon')));
$table->addColumn(new WV_Table_Column('Attributename'));
$table->addColumn(new WV_Table_Column('Feldtyp'));
$table->addColumn(new WV_Table_Column('Feldbezeichnung'));

$table->setIsEmpty(empty($data));
$table->setEmptyNotice('Sie haben noch keine Attribute angelegt.');

$table->enableDragAndDrop(count($data) > 1);
$table->setDragAndDropHandler('wv16.handleTableDrop');

$table->renderHeader(count($data));

foreach ($data as $attr) {
	?>
	<tr id="attr<?= $attr->getID() ?>">
		<td class="rex-icon"><a href="<?= $base ?>edit&amp;id=<?= $attr->getID() ?>"><img src="media/metainfo.gif" alt="" title="Attribut bearbeiten" /></a></td>
		<td><a href="<?= $base ?>edit&amp;id=<?= $attr->getID() ?>"><?= wv_html($attr->getName()) ?></a></td>
		<td><?= wv_html(WV_Datatype::getTitle($attr->getDatatypeID())) ?></td>
		<td><?= wv_html($attr->getTitle()) ?></td>
	</tr>
	<?
}

$table->renderFooter();
