# Kopiere diese Datei ins develop/config-Verzeichnis, um die Exporte im Backend
# zu aktivieren.
# Notiere hier als assoziative Liste die einzelnen Exporte. Pro Export müssen
# title, usertype und attributes angegeben werden. ID und Login werden immer
# mit exportiert.

frontenduser:
   be_columns:
      ___login___: Login
      ___registered___: Registrier-Datum

   # Callbacks dienen dazu, die Ausgabe von Zellinhalten noch einmal zu verändern
   # oder gänzlich eigene Inhalte pro Benutzer auszugeben. Dazu muss hier jeweils
   # der Key der Spalte (es funktionieren sowohl virtuelle Spalten wie ___id___
   # als auch eigene). Jeder Callback erhält drei Argumente: Den aktuellen
   # Benutzer, den Standardwert für diese Spalte (String) und den Namen (Key)
   # der Spalte (String).
   #
   #    myCallback(_WV16_User $user, $default, $column) { return ''; }
   #
   # Die zurückgegebenen Werte müssen bereits HTML-kodiert sein (= eigenes HTML
   # ist möglich).

#   be_column_callbacks:
#      ___id___: myCallback
#      mycol:    [myClass, myMethod]

   types:
      default: Standardbenutzer

#   rename_deleted_users: false # rename deleted users that are only marked as deleted

   attributes:
      firstname:
         title: Vorname
         datatype: stringline
         types: [default]
      email:
         title: E-Mail
         datatype: stringline
         types: [default]

   exports:
      users:
         title: Vollständige Benutzerdaten
         usertype: default
         attributes: [attribute1, attribute2, attribute3]
