DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_attributes`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_groups`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_rights`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_user_groups`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_user_values`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_users`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_utype_attrib`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_utypes`;
