DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_groups`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_user_groups`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_user_values`;
DROP TABLE IF EXISTS `%TABLE_PREFIX%wv16_users`;
