<?php
/*
 * Copyright (c) 2016, webvariants GmbH & Co. KG, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

print '<p>Die folgenden CSV-Exporte stehen zur Verfügung:</p>';

?>
<ul style="margin-left:25px">
	<?php foreach ($exports as $key => $info): ?>
	<li><a href="<?php print $_router->getUrl('frontenduser_exports', 'export', array('export' => $key)) ?>"><?php print sly_translate($info['title'], true) ?></a></li>
	<?php endforeach ?>
</ul>
