<?
if (!empty($errormsg)) {
	WV_redaxo::error($errormsg);
}

$form = new WV_Backend_Form('index.php', 'POST', 'Benutzertyp '.($func == 'add' ? 'erstellen' : 'bearbeiten'));

$form->addHiddenValue('page',    'frontenduser');
$form->addHiddenValue('subpage', 'types');
$form->addHiddenValue('func',     'do_'.$func);
$form->addHiddenValue('id',       $type ? $type->getID() : '');

////////////////////////////////////////////////////////////////////////////////
// Normale Felder

$name  = new WV_Form_Input_Text('name', 'Interner Name', $type ? $type->getName() : '');
$title = new WV_Form_Input_Text('title', 'Titel', $type ? $type->getTitle() : '');

$name->setHelpText('Über diesen Namen wird das Attribut programmseitig angsprochen.');
$title->setHelpText('Der Titel wird innerhalb von Redaxo in allen Formularen angezeigt.');

$form->addElements(array($name, $title));

////////////////////////////////////////////////////////////////////////////////
// Zugehörige Attribute

$form->beginFieldset('Die folgenden Attribute sind diesem Benutzertyp zugeordnet:');

$assignedAttributes  = $type ? $type->getAttributeIDs() : array();
$availableAttributes = WV16_Users::getAttributesForUserType(-1);
$attributes          = array();

foreach ($availableAttributes as $attr) {
	$attributes[$attr->getID()] = $attr->getTitle();
}

$attributes = new WV_Form_CheckboxGroup('attributes', 'Attribute', $assignedAttributes, $attributes);
$form->add($attributes);

////////////////////////////////////////////////////////////////////////////////
// Buttons festlegen

if ($type && $type->getID() != _WV16::DEFAULT_USER_TYPE) {
	$delete = new WV_Form_Button('submit', 'delete', 'Löschen');
	$delete->setAttribute('onclick', 'return confirm("Sicher, dass dieser Benutzertyp gelöscht werden soll?")');
	$form->setDeleteButton($delete);
}

$form->setFocus('name');
$form->render();
