</form>

<form action="index.php" method="post">

<div>
<input type="hidden" name="page" value="content" />
<input type="hidden" name="article_id" value="<?= $articleID ?>" />
<input type="hidden" name="mode" value="meta" />
<input type="hidden" name="save" value="1" />
<input type="hidden" name="clang" value="<?= $params['clang'] ?>" />
<input type="hidden" name="ctype" value="<?= isset($params['ctype']) ? $params['ctype'] : 1 ?>" />
</div>

<?php $hasRights = _WV16_FrontendUser::hasObjectRights($articleID, _WV16_FrontendUser::TYPE_ARTICLE); ?>

<fieldset class="rex-form-col-1">
	<legend class="rex-lgnd">Rechteverwaltung</legend>
	<div class="rex-fldst-wrppr rex-form-wrapper">

	<?php WV2_Form::startElement('Rechteverwaltung', 'frontenduser', 'checkbox') ?>
	<input type="checkbox" value="1" name="frontenduser" id="frontenduser" style="width:20px" <?= $hasRights ? 'checked="checked"' : '' ?>/> Zugriff auf diesen Artikel einschränken.
	<?php WV2_Form::closeElement() ?>

	<div id="frontenduserContainer" style="display:<?= $hasRights ? 'block' : 'none' ?>">

	<?php foreach (WV16_Users::getAllGroups('title', 'asc') as $group): ?>

		<?php $right = $group->canAccess($articleID, _WV16_FrontendUser::TYPE_ARTICLE) ? 1 : 0; ?>

		<?php WV2_Form::startElement($group->getTitle(), '_'.md5($group->getName()), 'text') ?>
		<input type="radio" value="1" name="<?= md5($group->getName()) ?>" <?= $right  ? ' checked="checked"' : '' ?> id="_<?= md5($group->getName()) ?>" style="width:20px" /> zulassen
		<input type="radio" value="0" name="<?= md5($group->getName()) ?>" <?= !$right ? ' checked="checked"' : '' ?> style="width:20px" /> verbieten
		<?php WV2_Form::closeElement() ?>

	<?php endforeach; ?>

	</div>

	<?php WV2_Form::buttonLine() ?>
	<input type="submit" name="saverights" class="rex-sbmt rex-form-submit" value="Rechte aktualisieren" />
	<?php WV2_Form::closeButtonLine() ?>

	</div>
</fieldset>

<script type="text/javascript">
jQuery(function($) {
	$('#frontenduser').click(function() { $('#frontenduserContainer').toggle(); });
});
</script>

</form>

<form action="index.php" method="post" enctype="multipart/form-data" id="REX_FORM2">

<div>
<input type="hidden" name="page" value="content" />
<input type="hidden" name="article_id" value="<?= $articleID ?>" />
<input type="hidden" name="mode" value="meta" />
<input type="hidden" name="save" value="1" />
<input type="hidden" name="clang" value="<?= $params['clang'] ?>" />
<input type="hidden" name="ctype" value="<?= isset($params['ctype']) ? $params['ctype'] : 1 ?>" />
</div>