<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

WV_Sally::p('Die folgenden CSV-Exporte stehen zur Verfügung:');
$base = 'index.php?page=frontenduser&amp;subpage=exports&amp;func=export&amp;export=';

?>
<ul style="margin-left:25px">
	<? foreach ($exports as $key => $info): ?>
	<li><a href="<?= $base.$key ?>"><?= sly_html($info['title']) ?></a></li>
	<? endforeach ?>
</ul>
