<?php
/*
 * Copyright (c) 2010, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

WV_Sally::p('Die folgenden Benutzer sind auf Ihrer Website registriert.');

$id      = '<a href="index.php?page=frontenduser&amp;func=add"><img src="../data/dyn/public/frontenduser/images/user_add.png" alt="" title="Hinzufügen" /></a>';
$table   = new sly_Table('users');
$columns = WV8_Settings::getValue('frontenduser', 'be_columns', array());

$table->addColumn(new sly_Table_Column($id, '', 'id', array('class' => 'rex-icon')));

foreach ($columns as $title) {
	$table->addColumn(new sly_Table_Column($title));
}

$table->setIsEmpty(empty($users));
$table->setEmptyNotice('Es haben sich noch keine Benutzer angemeldet.');
$table->enableSearching(true);
$table->enableSorting(true);

$table->renderHeader($total);

foreach ($users as $user) {
	?>
	<tr>
		<td class="rex-icon"><a href="index.php?page=frontenduser&amp;func=edit&amp;id=<?= $user->getID() ?>"><img src="../data/dyn/public/frontenduser/images/user.png" alt="" title="Benutzer bearbeiten" /></a></td>
		<?
		foreach ($columns as $name => $title) {
			print '<td>';

			switch ($name) {
				case '___login___':
					print '<a href="index.php?page=frontenduser&amp;func=edit&amp;id='.$user->getID().'">';
					print sly_html($user->getLogin());
					print '</a>';
					break;

				case '___type___':
					print sly_html($user->getType()->getTitle());
					break;

				case '___registered___':
					print sly_html(strftime('%d.%m.%Y um %H:%M Uhr', strtotime($user->getRegistered())));
					break;

				default:
					$value = $user->getValue($name);

					if ($value === null) {
						print '<td>&hellip;</td>';
						continue;
					}

					print sly_html($value->getValue());
					break;
			}

			print '</td>';
		}
		?>
	</tr>
	<?
}

$table->renderFooter();
