<?php
/*
 * Copyright (c) 2012, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

print '<p>Die folgenden Benutzer sind auf Ihrer Website registriert.</p>';

$id        = '<a href="index.php?page=frontenduser&amp;func=add"><img src="../data/dyn/public/webvariants/frontenduser/images/user_add.png" alt="" title="Hinzufügen" /></a>';
$table     = new sly_Table('users');
$columns   = array_merge(array('___id___' => ''), sly_Core::config()->get('frontenduser/be_columns', array()));
$callbacks = sly_Core::config()->get('frontenduser/be_column_callbacks', array());

$table->addColumn(new sly_Table_Column($id, '', 'id', array('class' => 'sly-icon')));

if (empty($columns)) {
	$columns = array('___login___' => 'Login');
}

foreach ($columns as $name => $title) {
	if ($name === '___id___') continue;
	$table->addColumn(new sly_Table_Column($title));
}

$table->setIsEmpty(empty($users));
$table->setEmptyNotice('Es haben sich noch keine Benutzer angemeldet.');
$table->enableSearching(true);
$table->enableSorting(true);

$table->openBuffer();

foreach ($users as $user) {
	?>
	<tr>
		<?
		foreach ($columns as $name => $title) {
			print $name === '___id___' ? '<td class="sly-icon">' : '<td>';

			switch ($name) {
				case '___id___':
					$value = '<a href="index.php?page=frontenduser&amp;func=edit&amp;id='.$user->getID().'"><img src="../data/dyn/public/webvariants/frontenduser/images/user.png" alt="" title="Benutzer bearbeiten" /></a>';
					break;

				case '___login___':
					$value  = '<a href="index.php?page=frontenduser&amp;func=edit&amp;id='.$user->getID().'">';
					$value .= sly_html($user->getLogin());
					$value .= '</a>';
					break;

				case '___type___':
					$value = sly_translate($user->getType()->getTitle(), true);
					break;

				case '___registered___':
					$value = sly_html(strftime('%d.%m.%Y um %H:%M Uhr', strtotime($user->getRegistered())));
					break;

				default:
					$value = $user->getValue($name);

					if ($value === null) {
						$value = '&hellip;';
						break;
					}

					if (is_scalar($value)) $value = sly_html($value);
					else $value = sly_Util_String::humanImplode(array_values($value));
			}

			if (isset($callbacks[$name])) {
				$value = call_user_func_array($callbacks[$name], array($user, $value, $name));
			}

			print $value;
			print '</td>';
		}
		?>
	</tr>
	<?
}

$table->closeBuffer();
print $table->render($total);
