<?php
/*
 * Copyright (c) 2011, webvariants GbR, http://www.webvariants.de
 *
 * This file is released under the terms of the MIT license. You can find the
 * complete text in the attached LICENSE file or online at:
 *
 * http://www.opensource.org/licenses/mit-license.php
 */

print '<p>Die folgenden Benutzer sind auf Ihrer Website registriert.</p>';

$id      = '<a href="index.php?page=frontenduser&amp;func=add"><img src="../sally/data/dyn/public/frontenduser/images/user_add.png" alt="" title="Hinzufügen" /></a>';
$table   = new sly_Table('users');
$columns = sly_Core::config()->get('frontenduser/be_columns', array());

$table->addColumn(new sly_Table_Column($id, '', 'id', array('class' => 'sly-icon')));

if (empty($columns)) {
	$columns = array('___login___' => 'Login');
}

foreach ($columns as $title) {
	$table->addColumn(new sly_Table_Column($title));
}

$table->setIsEmpty(empty($users));
$table->setEmptyNotice('Es haben sich noch keine Benutzer angemeldet.');
$table->enableSearching(true);
$table->enableSorting(true);

$table->openBuffer();

foreach ($users as $user) {
	?>
	<tr>
		<td class="sly-icon"><a href="index.php?page=frontenduser&amp;func=edit&amp;id=<?= $user->getID() ?>"><img src="../sally/data/dyn/public/frontenduser/images/user.png" alt="" title="Benutzer bearbeiten" /></a></td>
		<?
		foreach ($columns as $name => $title) {
			print '<td>';

			switch ($name) {
				case '___login___':
					print '<a href="index.php?page=frontenduser&amp;func=edit&amp;id='.$user->getID().'">';
					print sly_html($user->getLogin());
					print '</a>';
					break;

				case '___type___':
					print sly_html($user->getType()->getTitle());
					break;

				case '___registered___':
					print sly_html(strftime('%d.%m.%Y um %H:%M Uhr', strtotime($user->getRegistered())));
					break;

				default:
					$value = $user->getValue($name);

					if ($value === null) {
						print '&hellip;';
						break;
					}

					if (is_scalar($value)) print sly_html($value);
					else print sly_Util_String::humanImplode(array_values($value));
			}

			print '</td>';
		}
		?>
	</tr>
	<?
}

$table->closeBuffer();
print $table->render($total);
